# Generated by Django 3.1.7 on 2021-03-11 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя очереди')),
                ('is_private', models.BooleanField(default=False, verbose_name='Флаг закрытой очереди')),
                ('members', models.JSONField(default=list, verbose_name='Члены очереди')),
            ],
        ),
    ]
